var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/friendreq-test/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9c4a80cf._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_4c83e7d6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9b6e68fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6550089d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4538fb0c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_friendreq-test_page_actions_ffad2341.js")
R.m(73151)
module.exports=R.m(73151).exports
