var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/challenges/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fe31bdab._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_18698356._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9b6e68fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6550089d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4538fb0c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_challenges_page_actions_ad194d4f.js")
R.m(94585)
module.exports=R.m(94585).exports
